name: Publish Image

on:
    schedule:
        - cron: '0 2 1 * *'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              ref: master
          - name: Monthly build
            uses: HurricanKai/Publish-Docker-Github-Action@master
            if: contains(github.ref, 'refs/tags/')
            with:
              name: monolithprojects/systemd-ubuntu20
              username: monolithprojects
              password: ${{ secrets.TOKEN }}
              registry: docker.io
              dockerfile: Dockerfile
